### ISSUE TITLE
Updated list from another Repo

### ISSUE THREAD

**Issue by haseeb-heaven** [digitalemcee/chatgpt4-plugins#2]
Hi,
I have also updated the list of all chatgpt plugins with JSON and Table format.
You can get it here : [Chat-GPT Plugins List](https://github.com/haseeb-heaven/ChatGpt-Plugins-List)

**Comment by digitalemcee** [comment]
Thanks! Have you seen this searchable list? https://www.gptgames.dev/util/plugins.html
